apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-server
  labels:
    app: ubuntu
spec:
  containers:
    - name: ubuntu
      image: ubuntu:latest
      tty: true
      command: ["/bin/sh", "-c"]
      args:
        - |
          while true; do sleep 30; done
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
      securityContext:
        privileged: false
